package com.jbs.SpringBootHBTest.entity;

// default package
// Generated 12 Nov, 2020 9:30:15 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demo generated by hbm2java
 */
@Entity
@Table(name = "demo", catalog = "test")
public class Demo implements java.io.Serializable {

	private Integer id;
	private String name;

	public Demo() {
	}

	public Demo(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
